version: '3'

services:
  db:
    restart: always
    image: mysql:5.7
    container_name: docker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: demo
    ports:
      - "3306:3306"

  app:
    container_name: spring
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    links:
      - "db:docker-mysql"
    depends_on:
      - db
