spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: password

management:
  endpoint:
    info:
      enabled: true

logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %highlight(%-5level) %logger.%M - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger.%M - %msg%n"
  level:
    root: info
  file:
    name: logs/dev_app.log

---
spring:
  profiles: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa

management:
  endpoint:
    info:
      enabled: true

logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %highlight(%-5level) %logger.%M - %msg%n%ex{full}"
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger.%M - %msg%n"
  level:
    root: info
  file:
    name: logs/dev_app.log

---
spring:
  profiles: prod
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://docker-mysql:3306/${MYSQL_DATABASE}
    username: root
    password: ${MYSQL_PASSWORD}

management:
  endpoint:
    info:
      enabled: true

logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %highlight(%-5level) %logger.%M - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger.%M - %msg%n"
  level:
    root:
      warn
  file:
    name: logs/dev_app.log